### PR TITLE
Change current nav link to yellow

### PR DESCRIPTION
**Pull request by lindalu-MSFT**
The hsla opacity on the current nav link does not provide enough contrast for low vision or high contrast dark mode. Changed CSS from hsla() to accessibile yellow #FEF000

### CODE REVIEW

**Comment by lindalu-MSFT** [comment]
@PopWarner One more fix, then should be good! Thanks.

**Comment by lindalu-MSFT** [comment]
@PopWarner Can you please review and merge this one?

**Comment by VesaJuvonen** [comment]
Thx @lindalu-MSFT, getting merged and processed, so that we can close one more item from todo list.

**Comment by PopWarner** [comment]
Thank you @VesaJuvonen. Wasn't getting the alerts on this PR for some reason. Thank you again @lindalu-MSFT! 💜🧡

**Pull request merged**
